spring:
  datasource:
    url: jdbc:postgresql://database-1.crn27pdjfd0w.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: shin2244
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: create
server:
  port: 5001